replicaCount: 2
image:
  repository: ghcr.io/saimudunuri04/multimodal-search-service
  tag: "7bab825f84c569bb8f4299fb0aa86aca3ed22c93"
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  port: 8000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
env: {}
envFromSecretName: ""
volumeMounts: []
volumes: []
